fix: TypeError: fs.opendirSync is not a function (#201)
* grouped mocks and requires, mocks are hoisted anyway so order does not matter

closes #200